# Generated by Django 5.0.3 on 2024-03-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentals',
            name='user',
        ),
        migrations.AddField(
            model_name='properties',
            name='property_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='bedrooms',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='house_price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='house_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_contact',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
