# Generated by Django 5.0.3 on 2024-03-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_rentals_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentals',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
