# Generated by Django 5.0.3 on 2024-03-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_rentals_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentals',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
